### ISSUE TITLE
Expense Manger not working as expected

### ISSUE THREAD

**Issue by 53854** [53854/SWE_1#23]
Neue Ausgaben können momentan nur mit Namen angegeben werden, und müssen dann anschließen in der Edit Maske bearbeitet werden, aus welcher man nicht zurück zur eigenen Übersicht kommt.

Des Weitern zeigt die momentane Landing-Page einfach alle als "publish" gemarkten Umsätze an, was Nutzer verwirrt und jeglichen Datenschutz über den Haufen wirft. 

@bakenq @53854 fix pls 😱

**Comment by bakenq** [comment]
Die "publish" markierung wurde entfernt und die Landing-Page zeigt jetzt keine Expenses mehr an. Das hat aber vermutlich zur Folge das bereits existente Expenses neu erstellt werden müssen, da diese noch die "published" flag besitzen und das wahrscheinlich zu Problemen führt.
